name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm ci

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Build Backend
        working-directory: backend
        run: npm run build --if-present

      - name: Build Backend Image
        run: |
          docker build \
          -t taskflow-backend:latest \
          ./backend

      - name: Build Frontend Image
        run: |
          docker build \
          -t taskflow-frontend:latest \
          ./frontend
